FROM golang:1.24-bookworm AS backend-build
WORKDIR /app/backend

# Imagick (IM6) build deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config libmagickwand-6.q16-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN cd backend && go mod download

CMD cd backend && go test ./... -v