// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Privacy by Design Foundation"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/face-capture-config": {
            "get": {
                "description": "Returns the browser-reachable Regula Face API origin used by the /capture liveness page. The page runs the liveness session directly against that service, the same way the native Regula SDK does in the Play Store and App Store builds; only the resulting transaction ID is passed back to the app. Responds 404 when face verification is disabled, so the capture page cannot run liveness sessions no issuance will consume.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Face Verification"
                ],
                "summary": "Face capture page configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.FaceCaptureConfigResponse"
                        }
                    },
                    "404": {
                        "description": "face capture not configured",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        },
        "/issue-driving-licence": {
            "post": {
                "description": "Verifies the Electronic Driving Licence (EDL) and issues an IRMA credential. Returns a JWT that can be used with the IRMA server to obtain the credential. Passive authentication (SOD signature) is always mandatory. Active authentication (chip challenge-response) is mandatory when the chip supports it: if the chip carries an AA public key (DG13) the request must include a valid nonce and aa_signature, otherwise issuance is rejected with 400.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Driving Licence"
                ],
                "summary": "Verify and issue driving licence credential",
                "parameters": [
                    {
                        "description": "Validation request with document data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.IssuanceResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:internal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/issue-id-card": {
            "post": {
                "description": "Verifies the ID card and issues an IRMA credential. Returns a JWT that can be used with the IRMA server to obtain the credential. Passive authentication (SOD signature) is always mandatory. Active authentication (chip challenge-response) is mandatory when the chip supports it: if the chip carries an AA public key (DG15) the request must include a valid nonce and aa_signature, otherwise issuance is rejected with 400.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ID Card"
                ],
                "summary": "Verify and issue ID card credential",
                "parameters": [
                    {
                        "description": "Validation request with document data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.IssuanceResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:internal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/issue-passport": {
            "post": {
                "description": "Verifies the passport and issues an IRMA credential. Returns a JWT that can be used with the IRMA server to obtain the credential. Passive authentication (SOD signature) is always mandatory. Active authentication (chip challenge-response) is mandatory when the chip supports it: if the chip carries an AA public key (DG15) the request must include a valid nonce and aa_signature, otherwise issuance is rejected with 400.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passport"
                ],
                "summary": "Verify and issue passport credential",
                "parameters": [
                    {
                        "description": "Validation request with document data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.IssuanceResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:internal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/start-validation": {
            "post": {
                "description": "Initializes a new validation session and generates a nonce for active authentication. The nonce should be used to perform active authentication on the document chip. The session ID and nonce must be included in subsequent verification/issuance requests. The body is optional: a wallet may declare which face verification methods it can run (and, on a retry, which it was assigned before); no body means Regula only. When face verification is enabled for this environment, the response carries a face_verification object naming the assigned method and, for regula, the Face API the liveness session must run against; the app skips the face verification step when the object is absent. Responds 400 when none of the wallet's methods is enabled here.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "Start document validation session",
                "parameters": [
                    {
                        "description": "Optional capability declaration",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/main.StartValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ValidatePassportResponse"
                        }
                    },
                    "400": {
                        "description": "face verification required: please update the Yivi app",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:internal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/verify-driving-licence": {
            "post": {
                "description": "Verifies the authenticity of an Electronic Driving Licence (EDL) without issuing credentials. Performs both passive authentication (signature verification) and active authentication (chip challenge-response) if signature is provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Driving Licence"
                ],
                "summary": "Verify driving licence authenticity",
                "parameters": [
                    {
                        "description": "Validation request with document data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.VerificationResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:internal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/verify-passport": {
            "post": {
                "description": "Verifies the authenticity of a passport without issuing credentials. Performs both passive authentication (signature verification) and active authentication (chip challenge-response) if signature is provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passport"
                ],
                "summary": "Verify passport authenticity",
                "parameters": [
                    {
                        "description": "Validation request with document data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.VerificationResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:internal",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analytics.Client": {
            "type": "object",
            "properties": {
                "app_version": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "main.FaceCaptureConfigResponse": {
            "type": "object",
            "properties": {
                "face_api_url": {
                    "description": "Browser-reachable origin of the Regula Face API",
                    "type": "string",
                    "example": "https://faceapi.staging.yivi.app"
                }
            }
        },
        "main.FaceMatchResult": {
            "type": "object",
            "properties": {
                "matched": {
                    "description": "True if the document portrait and live face match above the similarity threshold",
                    "type": "boolean",
                    "example": true
                },
                "similarity": {
                    "description": "Similarity score between the document portrait and live face",
                    "type": "number",
                    "example": 0.92
                }
            }
        },
        "main.FaceMethod": {
            "type": "string",
            "enum": [
                "regula",
                "iris"
            ],
            "x-enum-varnames": [
                "MethodRegula",
                "MethodIris"
            ]
        },
        "main.FaceSessionAnnouncement": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "description": "Seconds until the session expires when streaming has not started",
                    "type": "integer",
                    "example": 600
                },
                "face_session_id": {
                    "type": "string",
                    "example": "fs_1a2b3c"
                },
                "stream_url": {
                    "description": "WebSocket endpoint of the verifier's stream for this session",
                    "type": "string",
                    "example": "wss://iris-verifier.staging.yivi.app/stream/fs_1a2b3c"
                },
                "token": {
                    "description": "Presented by the wallet as the first message on the stream",
                    "type": "string"
                }
            }
        },
        "main.FaceVerificationAnnouncement": {
            "type": "object",
            "properties": {
                "face_api_url": {
                    "description": "Browser/app-reachable origin of the Regula Face API the liveness session\nmust run against — the same service this issuer matches against. Present\nfor the regula method only.",
                    "type": "string",
                    "example": "https://faceapi.staging.yivi.app"
                },
                "method": {
                    "description": "The face verification method assigned to this session: regula or iris.\nWallets from before methods existed ignore it and run Regula, which is\nthe only method they are ever assigned.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/main.FaceMethod"
                        }
                    ],
                    "example": "regula"
                }
            }
        },
        "main.FaceVerificationDeclaration": {
            "type": "object",
            "properties": {
                "attempt": {
                    "description": "Set on a retry: the number of this attempt, starting at 2.",
                    "type": "integer"
                },
                "capabilities": {
                    "description": "Wire names of the methods this build can run. Absent or empty means\n[\"regula\"], the only method those wallets support. Unknown names are\nignored.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferred_method": {
                    "description": "A tester's preference, honoured only when allow_client_preference is on.",
                    "type": "string"
                },
                "previous_method": {
                    "description": "Set on a retry within one document flow: the method assigned last time.",
                    "type": "string"
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "description": "True if the service is healthy",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "main.IssuanceResponse": {
            "type": "object",
            "properties": {
                "irma_server_url": {
                    "description": "URL of the IRMA server for credential issuance",
                    "type": "string",
                    "example": "https://irma.example.com"
                },
                "jwt": {
                    "description": "Signed JWT containing the IRMA issuance request",
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "main.StartValidationRequest": {
            "type": "object",
            "properties": {
                "client": {
                    "description": "Coarse labels of the wallet build, for the recordings only.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/analytics.Client"
                        }
                    ]
                },
                "face_verification": {
                    "$ref": "#/definitions/main.FaceVerificationDeclaration"
                }
            }
        },
        "main.ValidatePassportResponse": {
            "type": "object",
            "properties": {
                "face_verification": {
                    "description": "Present iff face verification is enabled for this environment. Absent\nmeans the app skips the face verification step.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/main.FaceVerificationAnnouncement"
                        }
                    ]
                },
                "nonce": {
                    "description": "Random nonce for active authentication (16 hex characters)",
                    "type": "string",
                    "example": "1234567890abcdef"
                },
                "session_id": {
                    "description": "Unique session identifier (32 hex characters)",
                    "type": "string",
                    "example": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
                }
            }
        },
        "main.VerificationResponse": {
            "type": "object",
            "properties": {
                "authentic_chip": {
                    "description": "True if active authentication (chip challenge-response) succeeded",
                    "type": "boolean",
                    "example": true
                },
                "authentic_content": {
                    "description": "True if passive authentication (signature verification) succeeded",
                    "type": "boolean",
                    "example": true
                },
                "face_match": {
                    "description": "Optional face verification result",
                    "allOf": [
                        {
                            "$ref": "#/definitions/main.FaceMatchResult"
                        }
                    ]
                },
                "face_session": {
                    "description": "The Iris face session opened for this document; present only when the\nsession's assigned face verification method is iris",
                    "allOf": [
                        {
                            "$ref": "#/definitions/main.FaceSessionAnnouncement"
                        }
                    ]
                },
                "is_expired": {
                    "description": "True if the document has expired",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "models.ValidationRequest": {
            "type": "object",
            "properties": {
                "aa_signature": {
                    "description": "Hex-encoded active authentication signature (optional)",
                    "type": "string",
                    "example": "304502..."
                },
                "data_groups": {
                    "description": "Map of data group identifiers to hex-encoded data group contents",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ef_sod": {
                    "description": "Hex-encoded Security Object (EF.SOD) containing document signature",
                    "type": "string",
                    "example": "778201ab..."
                },
                "face_attempt": {
                    "description": "Which attempt at the face verification step this issuance follows within\nthe wallet's document flow, starting at 1. Recording only (optional).",
                    "type": "integer",
                    "example": 1
                },
                "face_duration_ms": {
                    "description": "Milliseconds from the user confirming the face verification intro to the\nevidence being in hand. Recording only (optional).",
                    "type": "integer",
                    "example": 4200
                },
                "face_session_id": {
                    "description": "Identifier of the Iris face session the issuer opened at verification.\nRequired at issuance when the session's assigned face verification\nmethod is iris; the issuer pulls the verdict for it (optional).",
                    "type": "string",
                    "example": "fs_1a2b3c"
                },
                "liveness_transaction_id": {
                    "description": "Identifier of a completed Regula liveness transaction. The live face\ncaptured during that session is compared against the document chip\nportrait for face verification (optional).",
                    "type": "string",
                    "example": "a1b2c3d4-5678-90ab-cdef-1234567890ab"
                },
                "nonce": {
                    "description": "Nonce obtained from /start-validation",
                    "type": "string",
                    "example": "1234567890abcdef"
                },
                "session_id": {
                    "description": "Session ID obtained from /start-validation",
                    "type": "string",
                    "example": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Go Passport Issuer API",
	Description:      "API for verifying and issuing digital credentials from travel documents (passports, ID cards, and driving licences).\nThis service validates MRTD (Machine Readable Travel Documents) and Electronic Driving Licences (EDL), then issues privacy-preserving credentials through the IRMA framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
